<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;
use Infinitypaul\LaravelPasswordHistoryValidation\Traits\PasswordHistoryTrait;
use Spatie\Permission\Traits\HasPermissions;
use Spatie\Permission\Traits\HasRoles;
use App\Traits\LogsActivityTrait;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes, LogsActivityTrait ,HasRoles,HasPermissions,PasswordHistoryTrait;

    protected static $logName = 'users';
    protected static $logAttributes = ['name', 'email', 'password','landing_page'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        $user = Auth::user();
        if ($user) {
            $level = $user->roles->pluck('level');
            static::addGlobalScope('checkLevel', function (Builder $builder) use ($level) {
                $builder->whereHas('roles', function ($query) use ($level) {
                    $query->where('level','>=',$level[0]);
                });
            });
        }
    }

    /*
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'landing_page',
        'enabled',
        'password_changed_at',
        'wrong_attempts',
        'last_login',
        'created_by',
        'updated_by'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function scopeTableData($query, $order_column, $order_by_str, $start, $length)
    {
        return $query->orderBy($order_column, $order_by_str)
            ->offset($start)
            ->limit($length);
    }

    public function scopeSearchData($query, $term)
    {
        return $query
            // ->Where('id', 'like', "%" . $term . "%")
            ->where('name', 'like', "%" . $term . "%")
            ->orWhere('email', 'like', "%" . $term . "%")
            ->orWhere('landing_page', 'like', "%" . $term . "%")
            ->orWhereHas('roles', function($query) use($term){
                $query->where('name', 'like', "%" . $term . "%");
            });
    }


}
